baseURL = "https://hugo-blog-oppoxa.netlify.app"
# title = "Hugo Themes"
author = "Steve Francia"
copyright = "Copyright © 2022, Oppoxa; all rights reserved."
paginate = 3
languageCode = "fr"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
theme = "hugo-paper"
title = "Oppoxa"


[params]
  twitter = 'oppoxa'
  github = 'oppoxa'
  instagram = 'oppoxa'

  avatar = 'hello@oppoxa.com'
  name = 'Oppoxa'
  bio = 'Oppo: A friend, associate or colleague.'

  description = "Nous pensons que le processus d'étude est une tâche qui dure toute la vie. Le blog vise à aider les étudiants à obtenir des conseils et des exemples concrets dans différents domaines."

# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
